apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hamster
  name: deploy
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hamster
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hamster
    spec:
      containers:
      - image: nginx
        name: deploy
        resources: {}
        securityContext:
          capabilities:
            drop:
              - ALL
        resources: {}
status: {}
